version: '3.9'
services:
  jupyter:
    build: .
    image: challenge-python
    container_name: challenge-python
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
